config/routes.rb
Rails.application.routes.draw do
  get 'order_items/create'
  get 'order_items/update'
  get 'order_items/destroy'

  root to: 'pages#home'

  devise_for :users
  resources :products, only: [:index, :show]

  resources :order_items
  resources :profiles, only: [:new, :edit, :create, :update]
  resource  :cart
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items

  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end

private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end


end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize


end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :product

  mount_uploader :image, ImageUploader
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items
  has_many :photos

    def set_total_price

    end
  
  end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :adress, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/shopping_cart.rb
class ShoppingCart
  attr_reader :products

#  def initialize(session = {})
  #  @products = []
#    @session_lines = session[:shopping_cart] || []
    #find session with value shopping cart, OR store an empy array
#    @order_lines = @session_lines.map do |line|
#      Orderline.from_hash(line)
#.map is converting a collection of something into another collection
#this is like .new, but with superpowers
#    end
# end

  def add_product(product, amount = 1)
    raise ArgumentError.new("This is not a product") unless product.is_a? Product

   #  @products << product
    @order_lines << Orderline.new(product, amount).to_hash
    #will be able to store itself on the session
  end

  class Orderline
    attr_writer  :added_at, :price
    attr_reader :product, :amount

      def initialize(product, amount)
        @product = product
        @product_id = product.id
        @amount = amount
        @added_at = Time.now
        @price = product.price
      end

      def to_hash
        {
          product_id: @product_id,
          amount: @amount,
          added_at: @added_at,
          price: @price,
        }
      end

      def from_hash(line_hash)
        product = Product.where(id: line_hash[:product_id]).first
        return if product.nil?
        #return nothing if we do not have a product
        order_line = OrderLine.new(product, line_hash[:amount])
        order_line.added_at = line_hash[:added_at]
        order_line.price = line_hash[:price]
        end
    end



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile

  def has_profile?
   profile.present? && profile.persisted?
 end

 def full_name
   profile.full_name
 end
 
end

app/controllers/cart_controller.rb
class CartController < ApplicationController

  def show
    #@order_items = current_order.order_items
  end

  def index
    @order_items = current_order.order_items
  end

  def update
    @product = Product.find(params[:id])
    current_cart << @product.id
    session[:shopping_cart] = current_cart
  end


end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
  #  @current_cart
    #@order_items = current_order.order_items
  end

  def index
    #@order_items = current_order.order_items
  end

  def update
    @product = Product.find(params[:id])
    current_cart << @product.id
    session[:shopping_cart] = current_cart


  end

  private

  def total_price
    @product = Product.find(params[:id])
    @total_price = current_cart.count * @product.price
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
#before_action :initiate_cart

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  #  @shopping_cart = initiate_cart
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:edit, :update]
  before_action :authenticate_user!

    def new
      @profile = Profile.new
    end

    def create
      @profile = current_user.build_profile(profile_params)

      if @profile.save
        redirect_to edit_profile_path(@profile), notice: "Profile successfully created"
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @profile.update(profile_params)
        redirect_to edit_profile_path(@profile), notice: "Profile successfully updated"
      else
        render :edit
      end
    end

    private
      def set_profile
        @profile = current_user.profile
      end

      def profile_params
        params.require(:profile).permit(:first_name, :last_name, :adress)
      end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurazon2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
  </head>

  <body>
  <%= render "shared/navbar" %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/shared/_form.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= @product.name %></small></h4>
    </div>
    <div class="col-xs-4">


      <%= form_for (@shopping_cart) do |f| %>

        <%= f.label :price %><br>
        <%= f.text_field :price %>

        <%= f.label :amount %><br>
        <%= f.number_field :amount, value: 1, class: "form-control", min: 1 %>

        <%= f.hidden_field :product_id, value: @product.product_id %>

        <%= f.submit "Add to Cart", class: "btn btn-primary" %>

      <% end %>

    </div>

  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Codaisseurazon", products_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">

        <% if !user_signed_in? %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Cart", cart_path %></li>
        <% else %>

        <li class="dropdown">

            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= current_user.has_profile? ? current_user.full_name : current_user.email  %> <span class="caret"></span></a>

            <ul class="dropdown-menu">

              <% if current_user.has_profile? %>
                <li><%= link_to "Edit Profile", edit_profile_path(current_user.profile) %></li>
              <% else %>
                <li><%= link_to "Create Profile", new_profile_path %></li>
              <% end %>
              <li><%= link_to "Edit Password", edit_user_registration_path %></li>

              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>
            
            <li><%= link_to "Cart", cart_path %></li>

        </li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>