config/routes.rb
Rails.application.routes.draw do
  get 'order_items/create'
  get 'order_items/update'
  get 'order_items/destroy'

  root to: 'pages#home'

  devise_for :users
  resources :products, only: [:index, :show]

  resources :order_items
  resources :profiles, only: [:new, :edit, :create, :update]
  resource  :cart
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items

  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end

private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end


end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize


end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :product

  mount_uploader :image, ImageUploader
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items
  has_many :photos

    def set_total_price

    end
  
  end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :adress, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/shopping_cart.rb
class ShoppingCart
  attr_reader :products

#  def initialize(session = {})
  #  @products = []
#    @session_lines = session[:shopping_cart] || []
    #find session with value shopping cart, OR store an empy array
#    @order_lines = @session_lines.map do |line|
#      Orderline.from_hash(line)
#.map is converting a collection of something into another collection
#this is like .new, but with superpowers
#    end
# end

  def add_product(product, amount = 1)
    raise ArgumentError.new("This is not a product") unless product.is_a? Product

   #  @products << product
    @order_lines << Orderline.new(product, amount).to_hash
    #will be able to store itself on the session
  end

  class Orderline
    attr_writer  :added_at, :price
    attr_reader :product, :amount

      def initialize(product, amount)
        @product = product
        @product_id = product.id
        @amount = amount
        @added_at = Time.now
        @price = product.price
      end

      def to_hash
        {
          product_id: @product_id,
          amount: @amount,
          added_at: @added_at,
          price: @price,
        }
      end

      def from_hash(line_hash)
        product = Product.where(id: line_hash[:product_id]).first
        return if product.nil?
        #return nothing if we do not have a product
        order_line = OrderLine.new(product, line_hash[:amount])
        order_line.added_at = line_hash[:added_at]
        order_line.price = line_hash[:price]
        end
    end



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile

  def has_profile?
   profile.present? && profile.persisted?
 end

 def full_name
   profile.full_name
 end
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_cart

  #  def initiate_cart
  #   @cart = ShoppingCart.new(session)
  #  end

   def current_cart
     session[:shopping_cart] ||= []
   end

end

app/controllers/cart_controller.rb
class CartController < ApplicationController

  def show
    #@order_items = current_order.order_items
  end

  def index
    @order_items = current_order.order_items
  end

  def update
    @product = Product.find(params[:id])
    current_cart << @product.id
    session[:shopping_cart] = current_cart
  end


end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
  #  @current_cart
    #@order_items = current_order.order_items
  end

  def index
    #@order_items = current_order.order_items
  end

  def update
    @product = Product.find(params[:id])
    current_cart << @product.id
    session[:shopping_cart] = current_cart


  end

  private

  def total_price
    @product = Product.find(params[:id])
    @total_price = current_cart.count * @product.price
  end
  
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
before_action :set_product
before_action :get_current_order

  def create
    session[:order] || = {}
    product_id = order_items_params[:product_id]
    amount = order_items_params[:amount]
    session[:order][product_id] || = 0
    session[:order][product_id] += amount
    redirect_to products_path
  end

  private

  def set_product
    @product = Product.all
  end

  def order_item_params
    params
    .require(:order_item)
    .permit(:product_id, :amount)
  end

  def get_current_order
    if !session[:order_id].nil?
      @current_order = Order.find(session[:order_id])
    else
      @current_order = Order.create
      @order_id = session[:order_id]
   end
 end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
#before_action :initiate_cart

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  #  @shopping_cart = initiate_cart
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:edit, :update]
  before_action :authenticate_user!

    def new
      @profile = Profile.new
    end

    def create
      @profile = current_user.build_profile(profile_params)

      if @profile.save
        redirect_to edit_profile_path(@profile), notice: "Profile successfully created"
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @profile.update(profile_params)
        redirect_to edit_profile_path(@profile), notice: "Profile successfully updated"
      else
        render :edit
      end
    end

    private
      def set_profile
        @profile = current_user.profile
      end

      def profile_params
        params.require(:profile).permit(:first_name, :last_name, :adress)
      end
  end

app/controllers/shopping_cart_controller.rb
class ShoppingCartController < ApplicationController
  before_action :initiate_cart

  def index
  end

  def create
    @shopping_cart.add_product(product_params)
  end

  def destroy
    #remove from @cart

  end


  def product_params
    params
    .require(:order_item)
    .permit(:product_id, :amount)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/cart/index.html.erb
<h1> Your Current Shopping Cart </h1>
<% current_cart.each do |product_id|%>
 <% @product = Product.find(product_id) %>
 <ul>
 <li> <%= @product.name %> </li>
 <li> <%= @product.price %> </li>
 </ul>
 <% end %>

app/views/carts/_products_in_cart.html.erb
<%= product.name %>

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<% if @order_items.size == 0 %>
  <p class="text-center">
    There are no items in your shopping cart.  Please <%= link_to "go back", products_path %> and add some items to your cart.
  </p>
<% else %>

  <% @order_items.each do |order_item| %>
    <%= render 'carts/products_in_cart', product: order_item.product, order_item: order_item, show_total: true %>
  <% end %>
<% end %>

app/views/carts/index.html.erb
<div class="shopping-cart">
  <%= render "shopping_cart" %>
</div>

app/views/carts/show.html.erb
<h1> Your Shopping Cart </h1>

<p> You now have <%= current_cart.count %> products in your cart </p>


<% current_cart.each do |product_id|%>
 <% @product = Product.find(product_id) %>
 <ul>
 <li> <%= @product.name %> - € <%= @product.price %> </li>
   <% @product.price = @productprice %>
 </ul>
 <% end %>
<%= link_to "PROCEED TO CHECKOUT" %>

app/views/order_items/create.html.erb
<h1>OrderItems#create</h1>
<p>Find me in app/views/order_items/create.html.erb</p>

app/views/order_items/destroy.html.erb
<h1>OrderItems#destroy</h1>
<p>Find me in app/views/order_items/destroy.html.erb</p>

app/views/order_items/index.html.erb
<h1> This are your ordered items: </h1>

<%= current_order.order_item_ids.product %>

app/views/order_items/update.html.erb
<h1>OrderItems#update</h1>
<p>Find me in app/views/order_items/update.html.erb</p>

app/views/products/index.html.erb
<h1>This is the list of all products</h1>

<% @products.each do |product| %>
  <ul>
  <li> <%= link_to product.name, product %>  -
    €<%= product.price %> </li>
  </ul>
    <% product.photos.each do |photo| %>
      <%= image_tag photo.image.thumbnail %>
    <% end %>
<% end %>

app/views/products/show.html.erb
<h1> <%= @product.name %> </h1>

<p> Description: <%= @product.description %> </p>

<h4> € <%= @product.price %> </h4>

<% @product.photos.each do |photo| %>
  <%= image_tag photo.image.thumbnail %>
  <% end %>

<%= link_to "ADD TO CART", cart_path(id: @product.id), method: :put %>


<%= current_cart %>

<h1> Your Shopping Cart </h1>
<% current_cart.each do |product_id|%>
 <% @product = Product.find(product_id) %>
 <ul>
 <li> <%= @product.name %> </li>
 <li> <%= @product.price %> </li>
 </ul>
 <% end %>

app/views/profiles/_form.html.erb
<%= form_for @profile do |f| %>
  <% @profile.errors.full_messages.each do |msg| %>
    <p class="alert alert-danger"><%= msg %></p>
  <% end %>

  <div class="form-group">
    <label>First Name</label>
    <%= f.text_field :first_name, placeholder: "First Name", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Last Name</label>
    <%= f.text_field :last_name, placeholder: "Last Name", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Adress</label>
    <%= f.text_field :adress, placeholder: "Whats your adress", class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
    <%= link_to "Back", root_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Edit your profile
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Create your profile
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>